wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    project: "EOS"
    job_type: "DATA8003-HW2"
    group: ""
    save_dir: "."
    name: ${experiment_name}_${running_time}
    reinit: true